In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import tensorflow as tf

In [2]:
# here the file name churn_modeling is being replaced by Bank.csv
df=pd.read_csv("Bank.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values 

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


#taking care of mising data
import numpy as np
from sklearn.impute import SimpleImputer
imputer =SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

'''encoding the categorical variable using label encoder
A label encoder is a commonly used tool in machine learning and data preprocessing.
Its primary function is to transform categorical data, which consists of labels or
text values, into numerical values. This is important because many machine learning
algorithms and models require numerical input data, and label encoding is one way to
convert categorical data into a suitable format for these algorithms.
'''

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])
print(x)
# here we have converted the categorical data into numeric one. MALE=1,FEMALE=0

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


as now we have to convert the geography colloum in to numeric one so has there is no relation between france
germany ,spain or any other country we use the the other method called ONE HOT ENCODING.

In [8]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
print(x_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


FEATURE SCALLING- IT IS THE MOST IMPORTANT STEP WHILE APPLYING THE ARTIFICIAL NEURAL NETWORK WE NEED
TO STANDARDIZE THE VALUES USING THE INBUILT LIBRARY IN PYTHON.

In [14]:
#FEATURE SCALING 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [15]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [16]:
print(x_test)

[[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504
   1.62356528]]


In [ ]:
#BUILDING THE ANN(ARTIFICIAL NEURAL NETWORK) USING TENSORFLOW KERAS MODEL

In [17]:
ann=tf.keras.models.Sequential()

In [18]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [21]:
ann.compile(optimizer='adam' ,loss='binary_crossentropy' ,metrics=['accuracy'] ,)

In [22]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 3ms/step - loss: 0.5697 - accuracy: 0.7958
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4884 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4485 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4339 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4289 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4257 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4233 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4210 - accuracy: 0.7966
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4191 - accuracy: 0.8165
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4172 - accura

In [26]:
ann.predict([[1,0,0,600,1,40,3,]])

1/1 [==============================] - 0s 48ms/step
[[False]]


Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [34]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [36]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

'''
[[True Negative (TN)  False Positive (FP)]
 [False Negative (FN)  True Positive (TP)]]
True Positive (TP): The number of correct positive predictions.
True Negative (TN): The number of correct negative predictions.
False Positive (FP): The number of incorrect positive predictions (Type I error).
False Negative (FN): The number of incorrect negative predictions (Type II error).
'''

[[1522   73]
 [ 209  196]]


0.859